/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mitumc.sdk;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        // Library classUnderTest = new Library();
        // assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
